// sidebar
export const SET_SELECTED_PAGE = 'SET_SELECTED_PAGE'
export const SET_COLLAPSE_STATE = 'SET_COLLAPSE_STATE'

//log
export const LOG_ITEM_ADDED = 'LOG_ITEM_ADDED'
export const LOG_CLEARED = 'LOG_CLEARED'
export const LOG_ITEMS_WAITING_CLEARED = 'LOG_ITEMS_WAITING_CLEARED'
export const LOG_ITEM_UPDATED = 'LOG_ITEM_UPDATED'
export const LOG_ITEM_ADDED_WITHOUT_DOUBLE_UP =
  'LOG_ITEM_ADDED_WITHOUT_DOUBLE_UP'

//PNETWORK
export const PNETWORK_PING_PONG = 'PNETWORK_PING_PONG'
export const PNETWORK_LAST_ISSUER_PROCESSED_BLOCK_LOADED =
  'PNETWORK_LAST_ISSUER_PROCESSED_BLOCK_LOADED'
export const PNETWORK_LAST_REDEEMER_PROCESSED_BLOCK_LOADED =
  'PNETWORK_LAST_REDEEMER_PROCESSED_BLOCK_LOADED'
export const PNETWORK_BLOCK_SUBMITTED = 'PNETWORK_BLOCK_SUBMITTED'
export const PNETWORK_RESET_BLOCK_SUBMIT_SUCCESS =
  'PNETWORK_RESET_BLOCK_SUBMIT_SUCCESS'
export const PNETWORK_REPORT_ISSUE_LOADED = 'PNETWORK_REPORT_ISSUE_LOADED'
export const PNETWORK_REPORT_REDEEM_LOADED = 'PNETWORK_REPORT_REDEEM_LOADED'
export const PNETWORK_RESET_DATA = 'PNETWORK_RESET_DATA'
export const PNETWORK_SET_ISSUER_BLOCK_HEIGHT_STATUS =
  'PNETWORK_SET_ISSUER_BLOCK_HEIGHT_STATUS'
export const PNETWORK_SET_REDEEMER_BLOCK_HEIGHT_STATUS =
  'PNETWORK_SET_REDEEMER_BLOCK_HEIGHT_STATUS'

//pTokens
export const SET_SELECTED_PTOKEN = 'SET_SELECTED_PTOKEN'
export const PTOKENS_BALANCE_LOADED = 'PTOKEN_BALANCE_LOADED'
export const PTOKENS_ISSUE_SUCCEDEED = 'PTOKENS_ISSUE_SUCCEDEED'
export const PTOKENS_ISSUE_NOT_SUCCEDEED = 'PTOKENS_ISSUE_NOT_SUCCEDEED'
export const PTOKENS_REDEEM_SUCCEDEED = 'PTOKENS_REDEEM_SUCCEDEED'
export const PTOKENS_REDEEM_NOT_SUCCEDEED = 'PTOKENS_REDEEM_NOT_SUCCEDEED'
export const PTOKENS_RESET_ISSUE_SUCCESS = 'PTOKENS_RESET_ISSUE_SUCCESS'
export const PTOKENS_RESET_REDEEM_SUCCESS = 'PTOKENS_RESET_REDEEM_SUCCESS'
export const PTOKENS_RESET_ISSUE_ERROR = 'PTOKENS_RESET_ISSUE_ERROR'
export const PTOKENS_RESET_REDEEM_ERROR = 'PTOKENS_RESET_REDEEM_ERROR'
export const PTOKENS_MINT_NONCE_LOADED = 'PTOKENS_MINT_NONCE_LOADED'
export const PTOKENS_BURN_NONCE_LOADED = 'PTOKENS_BURN_NONCE_LOADED'
export const PTOKENS_TOTAL_ISSUED_LOADED = 'PTOKENS_TOTAL_ISSUED_LOADED'
export const PTOKENS_TOTAL_REDEEMED_LOADED = 'PTOKENS_TOTAL_REDEEMED_LOADED'
export const PTOKENS_CIRCULATING_SUPPLY_LOADED =
  'PTOKENS_CIRCULATING_SUPPLY_LOADED'
export const PTOKENS_SET_DEPOSIT_ADDRESS = 'PTOKENS_SET_DEPOSIT_ADDRESS'
export const PTOKENS_RESET_DEPOSIT_ADDRESS = 'PTOKENS_RESET_DEPOSIT_ADDRESS'
export const PTOKENS_SET_PARAMS = 'PTOKENS_SET_PARAMS'
export const PTOKENS_RESET_PARAMS = 'PTOKENS_RESET_PARAMS'
export const PTOKENS_SET_NODE_INFO = 'PTOKENS_SET_NODE_INFO'

//wallets
export const WALLET_ISSUER_CONNECTED = 'WALLET_ISSUER_CONNECTED'
export const WALLET_REDEEMER_CONNECTED = 'WALLET_REDEEMER_CONNECTED'
export const WALLET_ISSUER_DISCONNECTED = 'WALLET_ISSUER_DISCONNECTED'
export const WALLET_REDEEMER_DISCONNECTED = 'WALLET_REDEEMER_DISCONNECTED'
export const WALLET_RESET_DATA = 'WALLET_RESET_DATA'

//network detector
export const NETWORK_DETECTED_REDEEMER = 'NETWORK_DETECTED_REDEEMER'
export const RESET_DETECTED_NETWORK_REDEEMER = 'RESET_DETECTED_NETWORK_REDEEMER'
