// general
export const DAPP_NAME = 'pTokens Dapp'

// nodes
export const PNETWORK_NODE_V3 = 'https://pnetwork-node-2a.eu.ngrok.io/v3'

// swap
export const ASSETS_LOADED = 'ASSETS_LOADED'
export const SWAP_BALANCE_LOADED = 'SWAP_BALANCE_LOADED'
export const SHOW_DEPOSIT_ADDRESS_MODAL = 'SHOW_DEPOSIT_ADDRESS_MODAL'
export const HIDE_DEPOSIT_ADDRESS_MODAL = 'HIDE_DEPOSIT_ADDRESS_MODAL'
export const PROGRESS_UPDATED = 'PROGRESS_UPDATED'
export const PROGRESS_RESET = 'PROGRESS_RESET'
export const UPDATE_SWAP_BUTTON = 'UPDATE_SWAP_BUTTON'
export const BPM_LOADED = 'BPM_LOADED'
export const SWAPPERS_BALANCES_LOADED = 'SWAPPERS_BALANCES_LOADED'

// nfts
export const NFTS_DATA_LOADED = 'NFTS_DATA_LOADED'
export const NFT_DATA_LOADED = 'NFT_DATA_LOADED'

// migrations
export const MIGRATION_ASSETS_LOADED = 'MIGRATION_ASSETS_LOADED'
export const MIGRATION_BALANCE_LOADED = 'MIGRATION_BALANCE_LOADED'
export const UPDATE_MIGRATE_BUTTON = 'UPDATE_MIGRATE_BUTTON'
export const MIGRATION_PROGRESS_UPDATED = 'MIGRATION_PROGRESS_UPDATED'
export const MIGRATION_PROGRESS_RESET = 'MIGRATION_PROGRESS_RESET'
export const APYS_LOADED = 'APYS_LOADED'

// wallets
export const WALLET_ETH_CONNECTED = 'WALLET_ETH_CONNECTED'
export const WALLET_ETH_DISCONNECTED = 'WALLET_ETH_DISCONNECTED'
export const WALLET_ETH_NETWORK_CHANGED = 'WALLET_ETH_NETWORK_CHANGED'
export const WALLET_ETH_ACCOUNT_CHANGED = 'WALLET_ETH_ACCOUNT_CHANGED'
export const WALLET_BSC_CONNECTED = 'WALLET_BSC_CONNECTED'
export const WALLET_BSC_DISCONNECTED = 'WALLET_BSC_DISCONNECTED'
export const WALLET_BSC_NETWORK_CHANGED = 'WALLET_BSC_CONNECTED'
export const WALLET_BSC_ACCOUNT_CHANGED = 'WALLET_BSC_CONNECTED'
export const WALLET_POLYGON_CONNECTED = 'WALLET_POLYGON_CONNECTED'
export const WALLET_POLYGON_DISCONNECTED = 'WALLET_POLYGON_DISCONNECTED'
export const WALLET_POLYGON_NETWORK_CHANGED = 'WALLET_POLYGON_NETWORK_CHANGED'
export const WALLET_POLYGON_ACCOUNT_CHANGED = 'WALLET_POLYGON_ACCOUNT_CHANGED'
export const WALLET_XDAI_CONNECTED = 'WALLET_XDAI_CONNECTED'
export const WALLET_XDAI_DISCONNECTED = 'WALLET_XDAI_DISCONNECTED'
export const WALLET_XDAI_NETWORK_CHANGED = 'WALLET_XDAI_NETWORK_CHANGED'
export const WALLET_XDAI_ACCOUNT_CHANGED = 'WALLET_XDAI_ACCOUNT_CHANGED'
export const WALLET_EOS_CONNECTED = 'WALLET_EOS_CONNECTED'
export const WALLET_EOS_DISCONNECTED = 'WALLET_EOS_DISCONNECTED'
export const WALLET_TELOS_CONNECTED = 'WALLET_TELOS_CONNECTED'
export const WALLET_TELOS_DISCONNECTED = 'WALLET_TELOS_DISCONNECTED'
export const WALLET_LIBRE_CONNECTED = 'WALLET_LIBRE_CONNECTED'
export const WALLET_LIBRE_DISCONNECTED = 'WALLET_LIBRE_DISCONNECTED'
export const WALLET_ULTRA_CONNECTED = 'WALLET_ULTRA_CONNECTED'
export const WALLET_ULTRA_DISCONNECTED = 'WALLET_ULTRA_DISCONNECTED'
export const WALLET_ARBITRUM_CONNECTED = 'WALLET_ARBITRUM_CONNECTED'
export const WALLET_ARBITRUM_DISCONNECTED = 'WALLET_ARBITRUM_DISCONNECTED'
export const WALLET_ARBITRUM_NETWORK_CHANGED = 'WALLET_ARBITRUM_NETWORK_CHANGED'
export const WALLET_ARBITRUM_ACCOUNT_CHANGED = 'WALLET_ARBITRUM_ACCOUNT_CHANGED'
export const WALLET_LUXOCHAIN_CONNECTED = 'WALLET_LUXOCHAIN_CONNECTED'
export const WALLET_LUXOCHAIN_DISCONNECTED = 'WALLET_LUXOCHAIN_DISCONNECTED'
export const WALLET_LUXOCHAIN_NETWORK_CHANGED = 'WALLET_LUXOCHAIN_NETWORK_CHANGED'
export const WALLET_LUXOCHAIN_ACCOUNT_CHANGED = 'WALLET_LUXOCHAIN_ACCOUNT_CHANGED'
export const WALLET_ALGORAND_CONNECTED = 'WALLET_ALGORAND_CONNECTED'
export const WALLET_ALGORAND_DISCONNECTED = 'WALLET_ALGORAND_DISCONNECTED'
export const WALLET_ALGORAND_ACCOUNT_CHANGED = 'WALLET_ALGORAND_ACCOUNT_CHANGED'
export const WALLET_FTM_CONNECTED = 'WALLET_FTM_CONNECTED'
export const WALLET_FTM_DISCONNECTED = 'WALLET_FTM_DISCONNECTED'
export const WALLET_FTM_ACCOUNT_CHANGED = 'WALLET_FTM_ACCOUNT_CHANGED'
export const WALLET_ORE_CONNECTED = 'WALLET_ORE_CONNECTED'
export const WALLET_ORE_DISCONNECTED = 'WALLET_ORE_DISCONNECTED'

// swap-old-pnt
export const ASSETS_LOADED_SWAP_OLD_PNT = 'ASSETS_LOADED_SWAP_OLD_PNT'

export const PTokenId = {
    PBTC_ON_ETH_MAINNET :'PBTC_ON_ETH_MAINNET',
    WBTC_ON_ETH_MAINNET:'WBTC_ON_ETH_MAINNET',
    PBTC_ON_EOS_MAINNET:'PBTC_ON_EOS_MAINNET',
    PBTC_ON_TELOS_MAINNET:'PBTC_ON_TELOS_MAINNET',
    PBTC_ON_LIBRE_MAINNET:'PBTC_ON_LIBRE_MAINNET',
    PBTC_ON_ARBITRUM_MAINNET:'PBTC_ON_ARBITRUM_MAINNET',
    PLTC_ON_ETH_MAINNET:'PLTC_ON_ETH_MAINNET',
    PLTC_ON_EOS_MAINNET:'PLTC_ON_EOS_MAINNET',
    PETH_ON_EOS_MAINNET:'PETH_ON_EOS_MAINNET',
    PNT_ON_EOS_MAINNET:'PNT_ON_EOS_MAINNET',
    PMKR_ON_EOS_MAINNET:'PMKR_ON_EOS_MAINNET',
    PLINK_ON_EOS_MAINNET:'PLINK_ON_EOS_MAINNET',
    PYFI_ON_EOS_MAINNET:'PYFI_ON_EOS_MAINNET',
    PTERIA_ON_EOS_MAINNET:'PTERIA_ON_EOS_MAINNET',
    PUNI_ON_EOS_MAINNET:'PUNI_ON_EOS_MAINNET',
    PBAND_ON_EOS_MAINNET:'PBAND_ON_EOS_MAINNET',
    PBAL_ON_EOS_MAINNET:'PBAL_ON_EOS_MAINNET',
    PCOMP_ON_EOS_MAINNET:'PCOMP_ON_EOS_MAINNET',
    PSNX_ON_EOS_MAINNET:'PSNX_ON_EOS_MAINNET',
    POMG_ON_EOS_MAINNET:'POMG_ON_EOS_MAINNET',
    PDAI_ON_EOS_MAINNET:'PDAI_ON_EOS_MAINNET',
    PANT_ON_EOS_MAINNET:'PANT_ON_EOS_MAINNET',
    PLRC_ON_EOS_MAINNET:'PLRC_ON_EOS_MAINNET',
    PUOS_ON_EOS_MAINNET:'PUOS_ON_EOS_MAINNET',
    PBAT_ON_EOS_MAINNET:'PBAT_ON_EOS_MAINNET',
    PREP_ON_EOS_MAINNET:'PREP_ON_EOS_MAINNET',
    PZRX_ON_EOS_MAINNET:'PZRX_ON_EOS_MAINNET',
    PPNK_ON_EOS_MAINNET:'PPNK_ON_EOS_MAINNET',
    PDOGE_ON_ETH_MAINNET:'PDOGE_ON_ETH_MAINNET',
    PEOS_ON_ETH_MAINNET:'PEOS_ON_ETH_MAINNET',
    PBTC_ON_BSC_MAINNET:'PBTC_ON_BSC_MAINNET',
    PBTC_ON_XDAI_MAINNET:'PBTC_ON_XDAI_MAINNET',
    PEOS_ON_POLYGON_MAINNET:'PEOS_ON_POLYGON_MAINNET',
    IQ_ON_ETH_MAINNET:'IQ_ON_ETH_MAINNET',
    TLOS_ON_ETH_MAINNET:'TLOS_ON_ETH_MAINNET',
    PNT_ON_BSC_MAINNET:'PNT_ON_BSC_MAINNET',
    PNT_ON_BSC_MAINNET_OLD:'PNT_ON_BSC_MAINNET_OLD',
    POPIUM_ON_BSC_MAINNET:'POPIUM_ON_BSC_MAINNET',
    PTERIA_ON_BSC_MAINNET:'PTERIA_ON_BSC_MAINNET',
    PDEFIPLUSPLUS_ON_BSC_MAINNET:'PDEFIPLUSPLUS_ON_BSC_MAINNET',
    CGG_ON_BSC_MAINNET:'CGG_ON_BSC_MAINNET',
    PBCP_ON_BSC_MAINNET:'PBCP_ON_BSC_MAINNET',
    PETH_ON_TELOS_MAINNET:'PETH_ON_TELOS_MAINNET',
    PLINK_ON_TELOS_MAINNET:'PLINK_ON_TELOS_MAINNET',
    PNT_ON_TELOS_MAINNET:'PNT_ON_TELOS_MAINNET',
    PUSDT_ON_TELOS_MAINNET:'PUSDT_ON_TELOS_MAINNET',
    PUSDT_ON_LIBRE_MAINNET:'PUSDT_ON_LIBRE_MAINNET',
    PUSDC_ON_TELOS_MAINNET:'PUSDC_ON_TELOS_MAINNET',
    PNT_ON_XDAI_MAINNET:'PNT_ON_XDAI_MAINNET',
    PRVN_ON_BSC_MAINNET:'PRVN_ON_BSC_MAINNET',
    TLOS_ON_BSC_MAINNET:'TLOS_ON_BSC_MAINNET',
    POPEN_ON_BSC_MAINNET:'POPEN_ON_BSC_MAINNET',
    OCP_ON_ETH_MAINNET:'OCP_ON_ETH_MAINNET',
    ANRX_ON_BSC_MAINNET:'$ANRX_ON_BSC_MAINNET',
    PBTC_ON_POLYGON_MAINNET:'PBTC_ON_POLYGON_MAINNET',
    TFF_ON_POLYGON_MAINNET:'TFF_ON_POLYGON_MAINNET',
    PSAFEMOON_ON_ETH_MAINNET:'PSAFEMOON_ON_ETH_MAINNET',
    EFX_ON_BSC_MAINNET:'EFX_ON_BSC_MAINNET',
    PSEEDS_ON_ETH_MAINNET:'PSEEDS_ON_ETH_MAINNET',
    PLBC_ON_BSC_MAINNET:'PLBC_ON_BSC_MAINNET',
    USDO_ON_POLYGON_MAINNET:'USDO_ON_POLYGON_MAINNET',
    GALA_ON_BSC_MAINNET:'GALA_ON_BSC_MAINNET',
    PUOS_ON_ULTRA_MAINNET:'PUOS_ON_ULTRA_MAINNET',
    EFX_ON_ETH_MAINNET:'EFX_ON_ETH_MAINNET',
    ZMT_ON_BSC_MAINNET:'ZMT_ON_BSC_MAINNET',
    BIST_ON_BSC_MAINNET:'BIST_ON_BSC_MAINNET',
    PNT_ON_POLYGON_MAINNET:'PNT_ON_POLYGON_MAINNET',
    PVAI_ON_ETH_MAINNET:'PVAI_ON_ETH_MAINNET',
    WSB_ON_ETH_MAINNET:'WSB_ON_ETH_MAINNET',
    PNT_ON_ARBITRUM_MAINNET:'PNT_ON_ARBITRUM_MAINNET',
    LUXO_ON_LUXOCHAIN_MAINNET:'LUXO_ON_LUXOCHAIN_MAINNET',
    LUXO_ON_BSC_MAINNET:'LUXO_ON_BSC_MAINNET',
    PETH_ON_ALGORAND_MAINNET:'PETH_ON_ALGORAND_MAINNET',
    PKEYS_ON_BSC_MAINNET:'PKEYS_ON_BSC_MAINNET',
    OATH_ON_ETH_MAINNET:'OATH_ON_ETH_MAINNET',
    PBTC_ON_ALGORAND_MAINNET:'PBTC_ON_ALGORAND_MAINNET',
    PUSDC_ON_ALGORAND_MAINNET:'PUSDC_ON_ALGORAND_MAINNET',
    USDC_ON_ALGORAND_MAINNET:'USDC_ON_ALGORAND_MAINNET',
    PUSDT_ON_ALGORAND_MAINNET:'PUSDT_ON_ALGORAND_MAINNET',
    USDT_ON_ALGORAND_MAINNET:'USDT_ON_ALGORAND_MAINNET',
    ORE_ON_ETH_MAINNET:'ORE_ON_ETH_MAINNET',
    PWOMBAT_ON_EOS_MAINNET:'PWOMBAT_ON_EOS_MAINNET',
    NUCO_ON_TELOS_MAINNET: 'NUCO_ON_TELOS_MAINNET',
    PFTM_ON_ETH_MAINNET: 'PFTM_ON_ETH_MAINNET',
}

export const TokenId = {
    ETH: 'ETH',
    FTM: 'FTM',
    EOS: 'EOS',
    BTC: 'BTC',
    LTC: 'LTC',
    DOGE: 'DOGE',
    UNI: 'UNI',
    ANT: 'ANT',
    BAL: 'BAL',
    BAND: 'BAND',
    BAT: 'BAT',
    COMP: 'COMP',
    DAI: 'DAI',
    LINK: 'LINK',
    LRC: 'LRC',
    MKR: 'MKR',
    OMG: 'OMG',
    PNK: 'PNK',
    PNT: 'PNT',
    PTERIA: 'PTERIA',
    REP: 'REP',
    SNX: 'SNX',
    UOS: 'UOS',
    YFI: 'YFI',
    ZRX: 'ZRX',
    IQ: 'IQ',
    TLOS: 'TLOS',
    OPIUM: 'OPIUM',
    DEFI_PLUS_PLUS: 'DEFI++',
    BCP: 'BCP',
    CGG: 'CGG',
    USDT: 'USDT',
    USDC: 'USDC',
    OPEN: 'OPEN',
    OCP: 'OCP',
    $ANRX: '$ANRX',
    TFF: 'TFF',
    EFX: 'EFX',
    SEEDS: 'SEEDS',
    USDO: 'USDO',
    GALA: 'GALA',
    ZMT: 'ZMT',
    BIST: 'BIST',
    VAI: 'VAI',
    WSB: 'WSB',
    LUXO: 'LUXO',
    KEYS: 'KEYS',
    OATH: 'OATH',
    NCDT: 'NCDT',
    ORE: 'ORE',
    WOMBAT: 'WOMBAT',
}

export const MigrationAssetId = {
PBTC_ON_ETH_MAINNET_V1_MIGRATION: 'PBTC_ON_ETH_MAINNET_V1_MIGRATION',
PBTC_ON_ETH_MAINNET_V2_MIGRATION: 'PBTC_ON_ETH_MAINNET_V2_MIGRATION',
PNT_ON_ETH_MAINNET: 'PNT_ON_ETH_MAINNET',
ETHPNT_ON_ETH_MAINNET:'ETHPNT_ON_ETH_MAINNET',
}

// curve pools
export const PBTC_ON_ETH_POOL = 'factory-v2-242'
export const TRANSFER_EVENT_TOPIC = '0xddf252ad1be2c89b69c2b068fc378daa952ba7f163c4a11628f55a4df523b3ef'
export const CURVE_MIN_AMOUNT = 0.000000001
export const CURVE_MAX_AMOUNT = 1000000
export const MAX_IMPACT = 0.1

export const Blockchain = {
    Ethereum: 'eth',
    XDAI: 'xdai',
    Polygon: 'polygon',
    BSC: 'bsc',
    EOS: 'eos',
    Telos: 'telos',
    Libre: 'libre',
    Bitcoin: 'btc',
    Litecoin: 'ltc',
    Dogecoin: 'doge',
    Ultra: 'ultra',
    Arbitrum: 'arbitrum',
    Luxochain: 'luxochain',
    Algorand: 'algorand',
    Fantom: 'fantom',
    Ore: 'ore',
}

export const Network = {
    Mainnet: 'mainnet'
}
