import { NetworkId } from 'ptokens-constants'

const swapAssets = [
  /* #################   pTokens   #################*/
  {
    address: '0x56112511EeDDC484EfDefCF18d4Ce28BDB542a1C',
    id: 'PUSDC_ON_XDAI_MAINNET',
    name: 'pUSDC',
    nativeDecimals: 6,
    network: 'mainnet',
    blockchain: 'XDAI',
    decimals: 18,
    symbol: 'pUSDC',
    isPtoken: true,
    nativeSymbol: 'USDC',
    nativeBlockchain: 'XDAI',
    image: 'pUSDC.svg',
    withBalanceDecimalsConversion: true,
    networkId: NetworkId.GnosisMainnet,
    underlyingAsset: 'USDC_ON_XDAI',
    isPerc20: true,
    isHidden: true,
  },
  {
    address: '0xff40059ab6e7250078963706496F05FB262dcEAF',
    id: 'PUSDC_ON_ARBITRUM_MAINNET',
    name: 'pUSDC',
    nativeDecimals: 6,
    network: 'testnet',
    blockchain: 'ARBITRUM',
    decimals: 18,
    symbol: 'pUSDC',
    isPtoken: true,
    nativeSymbol: 'USDC',
    nativeBlockchain: 'XDA',
    image: 'pUSDC.svg',
    withBalanceDecimalsConversion: true,
    networkId: NetworkId.ArbitrumMainnet,
    underlyingAsset: 'USDC_ON_XDAI',
    isPerc20: true,
  },
  /* #################   Native Tokens   #################*/
  {
    address: '0xDDAfbb505ad214D7b80b1f830fcCc89B60fb7A83',
    id: 'USDC_ON_XDAI',
    symbol: 'USDC',
    name: 'USD//C on xDai',
    network: 'mainnet',
    blockchain: 'XDAI',
    decimals: 6,
    isNative: true,
    nativeSymbol: 'USDC',
    nativeBlockchain: 'XDAI',
    image: 'USDC.svg',
    withBalanceDecimalsConversion: true,
    networkId: NetworkId.GnosisMainnet,
    isPerc20: true,
    pTokenAddress: '0x56112511EeDDC484EfDefCF18d4Ce28BDB542a1C',
  },
]

export default swapAssets
